const services=[
 {slug:'naver-place',icon:'N',title:'네이버 플레이스 · 지역검색 최적화',desc:'지역 검색에서 먼저 보이도록 플레이스와 콘텐츠 구조를 정리합니다.',items:['플레이스 정보 점검','진료과목·사진·소식 정리','지역 키워드 구조 설계','블로그·웹사이트 연결','리뷰 응대 방향 가이드']},
 {slug:'dental-content',icon:'✎',title:'치과 블로그 · 콘텐츠 마케팅',desc:'환자가 검색하는 질문을 신뢰를 만드는 콘텐츠로 바꿉니다.',items:['진료과목별 콘텐츠 기획','임플란트·교정·보철 콘텐츠','환자 질문 기반 글감','원장 철학 콘텐츠','의료광고 표현 점검']},
 {slug:'shorts-youtube',icon:'▶',title:'치과 쇼츠 · 유튜브 마케팅',desc:'원장님의 설명과 병원 분위기를 짧은 영상 콘텐츠로 만듭니다.',items:['원장 설명형 포맷 기획','진료 FAQ 주제 발굴','쇼츠·릴스·유튜브 기획','제목·썸네일·설명문 기획','의료광고 표현 점검']},
 {slug:'profile-photo',icon:'📷',title:'치과 의료진 프로필 · 병원 촬영',desc:'원장님과 병원 공간을 신뢰감 있는 이미지 자산으로 만듭니다.',items:['원장님 프로필 사진 기획','의료진 단체 및 개인 프로필 촬영 기획','진료실·상담실·대기실·장비 촬영 기획','네이버 플레이스용 사진 구성 제안','홈페이지·랜딩페이지용 이미지 구성 제안','블로그·SNS·쇼츠용 이미지 자산 정리','필요한 경우 전문 촬영 파트너 연계','촬영 후 마케팅 활용 방향 컨설팅']},
 {slug:'aeo-geo',icon:'AI',title:'AEO · GEO · AI 검색 최적화',desc:'AI 검색과 답변형 검색에 대비해 치과 정보를 구조화합니다.',items:['병원·원장·진료 엔티티 정리','FAQ 콘텐츠 구조화','지역·진료 키워드 설계','웹사이트 구조화 데이터','AI 검색 대응 콘텐츠']},
 {slug:'patient-funnel',icon:'↗',title:'상담 문의 · 내원 전환 설계',desc:'검색 유입이 상담과 내원 예약으로 이어지는 흐름을 설계합니다.',items:['전화·카카오·예약 연결','상담 CTA 위치 설계','문의 폼 구성','상담 스크립트 방향','리드 유입 경로 분석']},
 {slug:'ads',icon:'◎',title:'치과 광고 운영',desc:'검색과 소셜 광고를 진료과목별 랜딩과 연결합니다.',items:['네이버 검색광고','지역 키워드 광고','브랜드 검색광고','메타 광고','문의 흐름 분석']},
 {slug:'website-consulting',icon:'▣',title:'홈페이지 · 랜딩페이지 진단 및 제작 연계',desc:'상담 전환 구조를 진단하고 필요한 제작 방향과 파트너를 연결합니다.',items:['기존 홈페이지 전환 진단','진료과목별 페이지 구성','상담 CTA 흐름 점검','랜딩페이지 기획','검증된 제작 파트너 연계','제작 후 마케팅 활용 컨설팅']}
];
const serviceVisuals={
 'naver-place':{image:'/assets/images/service-naver-place-v1.webp',tag:'지역검색 최적화'},
 'dental-content':{image:'/assets/images/service-dental-content-v1.webp',tag:'콘텐츠 제작'},
 'shorts-youtube':{image:'/assets/images/service-shorts-youtube-v1.webp',tag:'영상 콘텐츠'},
 'profile-photo':{image:'/assets/images/service-profile-photo-v1.webp',tag:'브랜드 신뢰'},
 'aeo-geo':{image:'/assets/images/service-aeo-geo-v1.webp',tag:'AI 검색 최적화'},
 'patient-funnel':{image:'/assets/images/service-patient-funnel-v1.webp',tag:'상담 전환'},
 'ads':{image:'/assets/images/service-ads-v1.webp',tag:'광고 성과'},
 'website-consulting':{image:'/assets/images/service-website-consulting-v1.webp',tag:'웹사이트 제작'}
};
const pageVisuals={
 about:{image:'/assets/images/page-about-v1.webp',alt:'치과 진료실에서 마케팅 데이터를 함께 검토하는 덴탈인사이드 전문가와 의료진'},
 services:{image:'/assets/images/page-services-v1.webp',alt:'치과 마케팅 분석 화면과 촬영 장비가 놓인 실무 작업 공간'},
 cases:{image:'/assets/images/page-cases-v1.webp',alt:'치과 의료진과 마케팅 전문가가 성과 데이터를 분석하는 전략 회의'},
 process:{image:'/assets/images/page-process-v1.webp',alt:'진단부터 개선까지 치과 진료 계획과 상담 과정을 보여주는 장면'},
 insights:{image:'/assets/images/page-insights-v1.webp',alt:'치과 콘텐츠와 마케팅 인사이트를 제작하는 현대적인 작업 공간'},
 contact:{image:'/assets/images/page-contact-v1.webp',alt:'치과 상담실에서 친절하게 상담을 진행하는 전문가와 의료진'}
};
function applyServiceVisuals(){
 document.querySelectorAll('.service-card').forEach(card=>{
  const slug=card.getAttribute('href')?.split('/').filter(Boolean).pop();
  const visual=serviceVisuals[slug];
  const box=card.querySelector('.service-visual');
  if(visual&&box){
   const title=card.querySelector('h3')?.textContent||'서비스';
   box.innerHTML=`<img src="${visual.image}" alt="${title} 대표 이미지" loading="lazy">`;
   card.classList.add('has-service-image');
  }
 });
 const page=document.body.dataset.page||'';
 if(page.startsWith('service:')){
  const slug=page.split(':')[1];
  const visual=serviceVisuals[slug];
  const box=document.querySelector('.page-hero .hero-symbol');
  const title=document.querySelector('.page-hero h1')?.textContent||'서비스';
  if(visual&&box){
   box.classList.add('has-image');
   box.removeAttribute('aria-hidden');
   box.innerHTML=`<img src="${visual.image}" alt="${title} 대표 이미지"><span>${visual.tag}</span>`;
  }
 }else if(pageVisuals[page]){
  const visual=pageVisuals[page];
  const box=document.querySelector('.page-hero .hero-symbol');
  if(box){
   box.classList.add('has-image','has-page-image');
   box.removeAttribute('aria-hidden');
   box.innerHTML=`<img src="${visual.image}" alt="${visual.alt}">`;
  }
 }
}
const nav=`<header class="site-header"><div class="container nav-wrap"><a class="brand" href="/" aria-label="덴탈인사이드 홈"><span class="brand-mark"></span><span class="brand-copy">덴탈인사이드<small>DENTAL INSIDE</small></span></a><button class="menu-button" aria-label="메뉴 열기" aria-controls="primaryNavigation" aria-expanded="false">☰</button><nav class="nav-links" id="primaryNavigation" aria-label="주요 메뉴"><a href="/about/">회사소개</a><div class="nav-item"><button aria-expanded="false" aria-controls="serviceDropdown">서비스 소개⌄</button><div class="dropdown" id="serviceDropdown"><a href="/services/">서비스 전체</a>${services.map(s=>`<a href="/services/${s.slug}/">${s.title}</a>`).join('')}</div></div><a href="/cases/">성장사례</a><a href="/process/">프로세스</a><a href="/insights/">블로그</a><a href="/contact/">상담문의</a></nav><a class="nav-cta" href="/contact/">무료 진단 신청 →</a></div></header>`;
const footer=`<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="/"><span class="brand-mark"></span><span class="brand-copy">덴탈인사이드<small>DENTAL INSIDE</small></span></a><p>치과 전문 마케팅 에이전시.<br>검색 노출부터 상담과 내원 전환까지 함께 설계합니다.</p></div><div><h3 class="footer-title">회사</h3><div class="footer-links"><a href="/about/">회사 소개</a><a href="/services/">서비스 소개</a><a href="/cases/">성장사례</a><a href="/process/">프로세스</a><a href="/insights/">블로그</a></div></div><div><h3 class="footer-title">서비스</h3><div class="footer-links">${services.map(s=>`<a href="/services/${s.slug}/">${s.title}</a>`).join('')}</div></div><div><h3 class="footer-title">고객센터</h3><ul class="footer-contact"><li>☎ 02-1234-5678</li><li>✉ hello@dentalinside.co.kr</li><li>◷ 평일 09:00 - 18:00</li><li>네이버 · 유튜브 · 인스타그램</li></ul></div></div><div class="footer-bottom"><span>© 2026 덴탈인사이드 DENTAL INSIDE. All rights reserved.</span><span>개인정보처리방침　 이용약관</span></div></div></footer>`;
const cta=`<div class="container"><section class="cta-band"><div><h2>우리 치과의 마케팅 상태가 궁금하신가요?</h2><p>현재 채널과 상담 흐름을 먼저 진단해드립니다.</p></div><a class="button" href="/contact/">무료 진단 신청 →</a></section></div>`;
const serviceCards=()=>`<div class="service-grid">${services.map(s=>`<a class="service-card" href="/services/${s.slug}/"><div class="service-visual"><b>${s.icon}</b></div><h3>${s.title}</h3><p>${s.desc}</p><span class="more">자세히 보기 →</span></a>`).join('')}</div>`;
const pageHero=(eyebrow,title,desc,icon='🦷')=>`<section class="page-hero"><div class="container"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${desc}</p></div><div class="hero-symbol" aria-hidden="true">${icon}</div></div></section>`;
function home(){return `<main><section class="hero"><div class="hero-bg"></div><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">치과를 이해하는 마케팅, 결과로 증명합니다</p><h1>치과 산업을 아는 전문가가<em>상담과 내원 전환을</em>설계합니다</h1><p class="hero-lead">덴탈 플랫폼 경험과 치과 산업 이해를 바탕으로 온라인 마케팅 전략부터 실행, 성과 관리까지 치과에 최적화된 흐름을 제공합니다.</p><div class="hero-actions"><a class="button" href="/contact/">무료 진단 신청 →</a><a class="button outline" href="/cases/">성장사례 보기 →</a></div></div><aside class="hero-proof"><div class="proof-grid"><div><small>치과 전문 파트너</small><strong>3년+</strong></div><div><small>온라인 마케팅 실무</small><strong>13년+</strong></div><div><small>치과 네트워크</small><strong>200+</strong></div></div></aside></div></section><section class="trust-strip"><div class="container trust-grid"><div><strong>DENTAL INSIDE</strong><p>치과 업의 언어와 환자의 검색 의도를 함께 읽습니다.</p></div><div><strong>5년</strong><span>덴탈 플랫폼 실무 경험</span></div><div><strong>10년+</strong><span>온라인 마케팅 교육·실행</span></div><div><strong>데이터 기반</strong><span>진단 → 실행 → 개선</span></div></div></section><section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">CORE SERVICES</p><h2>덴탈인사이드 핵심 서비스</h2></div><p>채널 하나가 아니라, 환자가 치과를 발견하고 신뢰하고 문의하는 전체 여정을 연결합니다.</p></div>${serviceCards()}</div></section><section class="section alt"><div class="container"><div class="section-head"><div><p class="eyebrow">PROCESS</p><h2>치과 마케팅 성공 프로세스</h2></div><a class="more" href="/process/">전체 프로세스 보기 →</a></div><div class="process-row">${[['01','진단','현재 채널과 상담 흐름 점검'],['02','전략 설계','지역·진료과목별 방향 설정'],['03','콘텐츠·세팅','검색과 신뢰 자산 구축'],['04','실행','광고·콘텐츠·전환 운영'],['05','분석·개선','데이터 기반 지속 개선']].map(x=>`<article class="process-step"><b>${x[0]}</b><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></div></section><section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">SAMPLE REPORTS</p><h2>결과를 만들기 전, 구조부터 진단합니다</h2></div><p>실제 병원명이나 보장성 수치를 꾸미지 않습니다. 아래는 제공 가능한 분석 결과물의 예시입니다.</p></div><div class="case-grid">${['지역검색 구조 분석','상담 전환 진단 리포트','콘텐츠 유입 경로 점검'].map((x,i)=>`<article class="case-card"><div class="case-top"></div><div class="case-body"><small>SAMPLE 0${i+1}</small><h3>${x}</h3><p>현황·문제·우선순위·실행 제안을 한눈에 확인하는 샘플 리포트입니다.</p></div></article>`).join('')}</div></div></section><section class="section alt"><div class="container"><div class="section-head"><div><p class="eyebrow">WHY US</p><h2>왜 덴탈인사이드인가요?</h2></div></div><div class="reason-grid">${[['🦷','치과 산업 이해'],['✦','전문 마케팅 실행력'],['♙','병원 파트너십'],['⌁','데이터 기반 전략'],['✓','의료광고 가이드 준수']].map(x=>`<article class="reason"><i>${x[0]}</i><h3>${x[1]}</h3><p>과장보다 이해와 근거, 지속 가능한 운영을 우선합니다.</p></article>`).join('')}</div></div></section>${cta}</main>`}
function about(){return `<main>${pageHero('ABOUT DENTAL INSIDE','치과를 안다는 것과 마케팅을 안다는 것, 두 가지를 연결합니다.','덴탈인사이드는 치과 산업의 맥락과 온라인 마케팅 실행을 함께 이해하는 전문 파트너입니다.','DI')}<section class="section"><div class="container content-grid"><div class="sticky-copy"><p class="eyebrow">OUR BACKGROUND</p><h2>과장된 약속보다 업을 이해하는 진정성</h2><p>치과 원장님이 매일 마주하는 진료 현장과 환자가 온라인에서 치과를 선택하는 과정을 함께 봅니다.</p></div><div class="info-cards">${[['덴탈 플랫폼 5년 경험','국내 대형 덴탈 플랫폼의 콘텐츠와 마케팅 실무를 경험했습니다.'],['치과 의사 네트워크','치과 업계의 언어와 현장의 우선순위를 이해합니다.'],['온라인 마케팅 10년+','교육, 컨설팅, 콘텐츠와 실행을 연결해 왔습니다.'],['거상마케팅센터 운영','2023년부터 현장 중심의 마케팅 지원을 이어가고 있습니다.'],['병원 마케팅 파트너십','병원 전문 파트너와 협업해 필요한 실행 역량을 연결합니다.'],['안전한 표현 원칙','의료광고 가이드를 고려해 신뢰를 해치지 않는 커뮤니케이션을 지향합니다.']].map(x=>`<article class="info-card"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>${cta}</main>`}
function servicesPage(){return `<main>${pageHero('SERVICES','덴탈인사이드 서비스 소개','치과 마케팅은 검색 노출, 콘텐츠, 영상, 이미지, 상담 전환, 광고, 홈페이지 구조가 함께 연결될 때 성과로 이어집니다. 치과 산업 이해를 바탕으로 필요한 8가지 마케팅 요소를 통합적으로 설계합니다.','8')}<section class="section"><div class="container">${serviceCards()}</div></section><section class="section alt"><div class="container content-grid"><div class="sticky-copy"><p class="eyebrow">WHERE TO START</p><h2>무엇부터 해야 할지 모르겠다면</h2><p>현재 채널 상태, 주력 진료과목, 지역 경쟁과 상담 흐름을 먼저 살펴봅니다.</p></div><div class="check-grid">${['검색 노출이 부족한가','콘텐츠와 이미지의 신뢰가 약한가','문의가 예약으로 이어지는가','광고와 랜딩이 연결되는가'].map(x=>`<div class="check">${x}</div>`).join('')}</div></div></section>${cta}</main>`}
function profilePhotoDetail(){const needs=['홈페이지나 플레이스에 사용할 전문 사진이 부족한 치과','원장님과 의료진의 신뢰감을 보여주고 싶은 치과','블로그, SNS, 쇼츠·유튜브에 쓸 이미지 자산이 필요한 치과','병원 공간과 진료 장비를 더 전문적으로 보여주고 싶은 치과','오래된 사진 때문에 브랜드 이미지가 약해 보이는 치과'];const uses=['홈페이지 메인 이미지','원장님 소개 페이지','네이버 플레이스 사진','블로그 대표 이미지','인스타그램·릴스·쇼츠 썸네일','유튜브 채널 이미지','광고 랜딩페이지','병원 소개서·제안서'];const effects=['원장님과 의료진의 신뢰감 향상','병원 공간의 전문성 전달','플레이스와 홈페이지의 첫인상 개선','블로그와 SNS 콘텐츠 품질 향상','상담 전환에 필요한 시각 자료 확보'];const steps=[['01','진단','현재 보유한 사진과 콘텐츠 자산을 점검합니다.'],['02','촬영 기획','원장님, 의료진, 공간, 장비, 상담 장면 등 필요한 촬영 리스트를 정리합니다.'],['03','촬영 또는 파트너 연계','내부 기획에 맞춰 촬영을 진행하거나 전문 촬영 파트너와 연결합니다.'],['04','콘텐츠 활용 설계','결과물을 홈페이지, 플레이스, 블로그, SNS와 광고에 어떻게 쓸지 정리합니다.'],['05','개선','반응이 좋은 이미지와 콘텐츠를 기준으로 지속 개선합니다.']];const s=services.find(x=>x.slug==='profile-photo');return `<main>${pageHero('DENTAL TRUST ASSETS','치과 의료진 프로필 · 병원 촬영','원장님과 병원의 신뢰감을 사진과 영상 콘텐츠로 보여드립니다. 환자는 치료를 결정하기 전에 원장님의 인상, 병원의 분위기, 진료실의 청결감, 장비와 상담 환경을 함께 봅니다. 덴탈인사이드는 마케팅에 활용할 촬영 콘텐츠를 기획하고 필요한 경우 전문 촬영 파트너와 연계합니다.','📷')}<section class="section"><div class="container content-grid"><div class="sticky-copy"><p class="eyebrow">WHY IT MATTERS</p><h2>이런 치과에 필요합니다</h2><p>한 번의 촬영이 아니라 여러 마케팅 채널에서 오래 활용할 수 있는 신뢰 이미지 자산을 구축합니다.</p><a class="button" href="/contact/">무료 진단 신청 →</a></div><div><div class="check-grid">${needs.map(x=>`<div class="check">${x}</div>`).join('')}</div><div class="section-head" style="margin:55px 0 24px"><div><p class="eyebrow">WHAT WE DO</p><h2>덴탈인사이드가 하는 일</h2></div></div><div class="info-cards">${s.items.map((x,i)=>`<article class="info-card"><h3>${String(i+1).padStart(2,'0')} · ${x}</h3><p>치과의 전문성과 청결감, 상담에 필요한 신뢰가 자연스럽게 전달되도록 촬영 목록과 활용 방향을 함께 설계합니다.</p></article>`).join('')}</div></div></div></section><section class="section alt"><div class="container"><div class="section-head"><div><p class="eyebrow">CONTENT USE</p><h2>촬영 콘텐츠 활용처</h2></div><p>한 번 만든 이미지 자산을 채널의 목적과 화면 비율에 맞춰 체계적으로 활용합니다.</p></div><div class="check-grid">${uses.map(x=>`<div class="check">${x}</div>`).join('')}</div></div></section><section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">WORKFLOW</p><h2>진행 방식</h2></div></div><div class="process-row">${steps.map(x=>`<article class="process-step"><b>${x[0]}</b><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></div></section><section class="section alt"><div class="container content-grid"><div class="sticky-copy"><p class="eyebrow">EXPECTED VALUE</p><h2>기대할 수 있는 변화</h2><p>과장된 성과를 약속하지 않습니다. 환자가 치과를 이해하는 데 필요한 시각 정보의 품질과 일관성을 높입니다.</p></div><div class="check-grid">${effects.map(x=>`<div class="check">${x}</div>`).join('')}</div></div></section><div class="container"><section class="cta-band"><div><h2>우리 치과에 필요한 사진과 영상 자산을 점검해보세요</h2><p>보유 이미지와 활용 채널을 살펴보고 필요한 촬영 범위를 함께 정리합니다.</p></div><a class="button" href="/contact/">무료 진단 신청 →</a></section></div></main>`}
function serviceDetail(slug){if(slug==='profile-photo')return profilePhotoDetail();const s=services.find(x=>x.slug===slug)||services[0];return `<main>${pageHero('DENTAL MARKETING SERVICE',s.title,s.desc,s.icon)}<section class="section"><div class="container content-grid"><div class="sticky-copy"><p class="eyebrow">WHY IT MATTERS</p><h2>이런 치과에 필요합니다</h2><p>단순 채널 운영보다 환자가 정보를 발견하고 신뢰한 뒤 상담으로 이어지는 연결 구조가 필요한 경우에 적합합니다.</p><a class="button" href="/contact/">우리 치과에 맞는지 상담 →</a></div><div><div class="check-grid">${['현재 채널의 역할이 불분명합니다','검색 유입이 상담으로 이어지지 않습니다','콘텐츠가 진료 강점을 설명하지 못합니다','실행 후 무엇을 개선할지 알기 어렵습니다'].map(x=>`<div class="check">${x}</div>`).join('')}</div><div class="section-head" style="margin:55px 0 24px"><div><p class="eyebrow">WHAT WE DO</p><h2>덴탈인사이드가 하는 일</h2></div></div><div class="info-cards">${s.items.map((x,i)=>`<article class="info-card"><h3>${String(i+1).padStart(2,'0')} · ${x}</h3><p>현재 상태를 확인하고, 치과의 진료 방향과 환자 관점에 맞는 실행안을 정리합니다.</p></article>`).join('')}</div></div></div></section><section class="section alt"><div class="container"><div class="section-head"><div><p class="eyebrow">WORKFLOW</p><h2>진행 방식</h2></div></div><div class="process-row">${[['01','진단'],['02','설계'],['03','세팅'],['04','실행'],['05','리포트']].map(x=>`<article class="process-step"><b>${x[0]}</b><h3>${x[1]}</h3><p>현황과 데이터를 바탕으로 다음 단계의 우선순위를 정합니다.</p></article>`).join('')}</div></div></section>${cta}</main>`}
function processPage(){return `<main>${pageHero('HOW WE WORK','진단부터 개선까지, 보이는 5단계 프로세스','치과 원장님이 지금 무엇을 하고 있고 다음에 무엇이 진행되는지 알 수 있도록 투명하게 공유합니다.','→')}<section class="section"><div class="container timeline">${[['01','진단','현재 홈페이지, 플레이스, 블로그, 광고와 상담 흐름을 분석합니다.'],['02','전략 설계','지역, 진료과목, 경쟁 환경과 환자 검색 의도를 바탕으로 우선순위를 세웁니다.'],['03','콘텐츠 · 세팅','홈페이지, 블로그, 플레이스, FAQ, 의료진 프로필, 병원 공간 사진과 쇼츠·유튜브 영상까지 콘텐츠 자산으로 정리합니다.'],['04','실행','광고, 콘텐츠 발행, 검색 최적화와 상담 전환 흐름을 운영합니다.'],['05','분석 · 개선','상담 문의, 유입과 전환 데이터를 바탕으로 지속적으로 개선합니다.']].map(x=>`<article class="timeline-item"><div class="timeline-num">${x[0]}</div><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div></section>${cta}</main>`}
function cases(){const cards=[['치과 맞춤 진단 리포트','현황과 개선 우선순위를 구체적인 체크리스트로 정리하는 샘플입니다.'],['상담 전환 개선 설계','검색 유입부터 문의와 예약까지의 흐름을 점검하는 샘플입니다.'],['지역검색 구조 분석','지역·진료과목 검색 구조와 채널 연결을 살펴보는 샘플입니다.'],['블로그 유입·예약 흐름 점검','콘텐츠 유입 이후 상담 동선을 확인하는 샘플입니다.'],['의료진 프로필 · 병원 이미지 개선','오래된 사진을 원장님 프로필, 진료실, 상담실과 장비 이미지 중심으로 재구성해 홈페이지와 플레이스 첫인상을 개선하는 프로젝트 예시입니다.'],['병원 마케팅 파트너 협업 체계','필요한 전문 역량을 파트너와 연결하는 협업 범위 안내입니다.']];return `<main>${pageHero('CASES & REPORTS','성과를 꾸미지 않고, 진단과 개선의 근거를 보여드립니다.','현재 공개 가능한 실명 사례 대신 실제 상담에서 제공할 수 있는 분석 결과물과 협업 경험의 범위를 안내합니다.','↗')}<section class="section"><div class="container"><div class="notice">아래 카드는 샘플과 프로젝트 예시입니다. 특정 병원의 실제 성과나 보장 수치를 의미하지 않습니다.</div><div class="case-grid" style="margin-top:24px">${cards.map((x,i)=>`<article class="case-card"><div class="case-top"></div><div class="case-body"><small>SAMPLE 0${i+1}</small><h3>${x[0]}</h3><p>${x[1]}</p></div></article>`).join('')}</div></div></section>${cta}</main>`}
function insights(){const posts=[['치과 마케팅 전략','광고보다 먼저 상담 흐름을 봐야 하는 이유'],['네이버 플레이스','플레이스 정보, 무엇부터 점검해야 할까요?'],['치과 블로그','환자가 검색하는 질문을 콘텐츠로 바꾸는 법'],['쇼츠 · 유튜브','쇼츠·유튜브 촬영 전 준비해야 할 치과 이미지 자산'],['치과 프로필 사진 · 병원 촬영','치과 원장님 프로필 사진이 상담 전환에 중요한 이유'],['치과 프로필 사진 · 병원 촬영','네이버 플레이스에 꼭 필요한 치과 사진 구성'],['치과 프로필 사진 · 병원 촬영','치과 홈페이지에 들어가야 할 병원 사진 7가지'],['치과 프로필 사진 · 병원 촬영','쇼츠·유튜브 촬영 전 준비해야 할 치과 이미지 자산'],['AEO · GEO','AI 검색을 위한 치과 FAQ 구조'],['의료광고 주의사항','치과 콘텐츠 표현 전 확인할 기준'],['상담 전환','문의 폼보다 먼저 점검할 상담 동선']];return `<main>${pageHero('DENTAL MARKETING INSIGHTS','치과 마케팅을 더 선명하게 이해하는 인사이트','현장에서 자주 듣는 질문과 채널별 실무 포인트를 부담 없이 읽을 수 있게 정리합니다.','✎')}<section class="section"><div class="container"><div class="article-grid">${posts.map(x=>`<article class="article-card"><small>${x[0]}</small><h3>${x[1]}</h3><p>덴탈인사이드 인사이트에 게시될 글의 주제와 구성 예시입니다. 준비 중인 콘텐츠입니다.</p></article>`).join('')}</div></div></section>${cta}</main>`}
function contact(){return `<main>${pageHero('FREE DIAGNOSIS','우리 치과의 현재 마케팅 상태를 먼저 진단해보세요.','입력해주신 내용을 바탕으로 우선 확인할 채널과 상담 흐름을 정리해 연락드립니다.','☎')}<section class="section"><div class="container contact-layout"><aside class="contact-card"><p class="eyebrow">CONTACT</p><h2>무료 진단 신청</h2><p>서비스 계약 전, 지금 필요한 것이 무엇인지부터 함께 확인합니다.</p><ul><li>02-1234-5678</li><li>hello@dentalinside.co.kr</li><li>평일 09:00 - 18:00</li></ul></aside><form class="contact-form" id="contactForm"><div class="field"><label for="clinic">치과명 *</label><input id="clinic" name="clinic" required></div><div class="field"><label for="contactName">원장님 / 담당자명 *</label><input id="contactName" name="name" required></div><div class="field"><label for="phone">연락처 *</label><input id="phone" name="phone" type="tel" inputmode="tel" required></div><div class="field"><label for="email">이메일</label><input id="email" name="email" type="email" inputmode="email"></div><div class="field"><label for="region">지역</label><input id="region" name="region"></div><div class="field"><label for="service">관심 서비스</label><select id="service" name="service"><option value="">선택해 주세요</option>${services.map(s=>`<option>${s.title}</option>`).join('')}</select></div><div class="field full"><label for="website">홈페이지 주소</label><input id="website" name="website" type="url" inputmode="url" placeholder="https://"></div><div class="field full"><label for="place">네이버 플레이스 주소</label><input id="place" name="place" type="url" inputmode="url" placeholder="https://"></div><div class="field full"><label for="message">현재 고민</label><textarea id="message" name="message"></textarea></div><div class="field full"><label for="preferredTime">상담 희망 시간</label><select id="preferredTime" name="preferredTime"><option value="">선택해 주세요</option><option>오전 09:00 - 12:00</option><option>오후 12:00 - 15:00</option><option>오후 15:00 - 18:00</option><option>시간 협의</option></select></div><label class="consent" for="privacyConsent"><input id="privacyConsent" type="checkbox" required> 개인정보 수집 및 상담 연락에 동의합니다.</label><button class="button" type="submit">무료 진단 신청하기 →</button><div class="form-message" role="status" aria-live="polite">신청 내용이 임시 접수되었습니다. 실제 전송 기능은 추후 연동할 수 있습니다.</div></form></div></section></main>`}
function render(){const p=document.body.dataset.page;let content=home();if(p==='about')content=about();else if(p==='services')content=servicesPage();else if(p?.startsWith('service:'))content=serviceDetail(p.split(':')[1]);else if(p==='process')content=processPage();else if(p==='cases')content=cases();else if(p==='insights')content=insights();else if(p==='contact')content=contact();document.querySelector('#app').innerHTML=nav+content+footer;applyServiceVisuals();bind()}
function bind(){const menu=document.querySelector('.menu-button'),links=document.querySelector('.nav-links'),serviceToggle=document.querySelector('.nav-item>button'),navItem=document.querySelector('.nav-item');const closeMenus=()=>{links?.classList.remove('open');navItem?.classList.remove('open');menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label','메뉴 열기');serviceToggle?.setAttribute('aria-expanded','false')};menu?.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기')});serviceToggle?.addEventListener('click',()=>{const open=navItem.classList.toggle('open');serviceToggle.setAttribute('aria-expanded',String(open))});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenus()});const current=location.pathname.replace(/\/+$/,'')||'/';document.querySelectorAll('.nav-links a,.nav-cta').forEach(a=>{const target=new URL(a.href,location.origin).pathname.replace(/\/+$/,'')||'/';if(target===current)a.setAttribute('aria-current','page')});document.querySelector('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();e.currentTarget.querySelector('.form-message').classList.add('show');e.currentTarget.querySelector('button').textContent='임시 접수 완료 ✓'})}
render();
